
setup cmake

export G4DATADIR=/home/gonzalo/data/geant4/
export G4DIR=$SWDIR/geant4/install
export CMAKE_PREFIX_PATH=$G4DIR:${CMAKE_PREFIX_PATH}

source $G4DIR/bin/geant4.sh

export G4ABLADATA=$G4DATADIR/G4ABLA3.1
export G4ENSDFSTATEDATA=$G4DATADIR/G4ENSDFSTATE2.3
export G4INCLDATA=$G4DATADIR/G4INCL1.0
export G4LEDATA=$G4DATADIR/G4EMLOW8.0
export G4LEVELGAMMADATA=$G4DATADIR/PhotonEvaporation5.7
export G4NEUTRONHPDATA=$G4DATADIR/G4NDL4.6
export G4PARTICLEXSDATA=$G4DATADIR/G4PARTICLEXS4.0
export G4PIIDATA=$G4DATADIR/G4PII1.3
export G4RADIOACTIVEDATA=$G4DATADIR/RadioactiveDecay5.6
export G4REALSURFACEDATA=$G4DATADIR/RealSurface2.2
export G4SAIDXSDATA=$G4DATADIR/G4SAIDDATA2.0
