export NUCDDIR=$GITDIR/nuCD
export PATH=$PATH:$NUCDDIR/EI/bin
export LIBPATH=$LIBPATH:$NUCDDIR/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/$NUCDDIR/EI/lib
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/$NUCDDIR/EI/lib